<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| File and Directory Modes
|--------------------------------------------------------------------------
|
| These prefs are used when checking and setting modes when working
| with the file system.  The defaults are fine on servers with proper
| security, but you may wish (or even need) to change the values in
| certain environments (Apache running a separate process for each
| user, PHP under CGI with Apache suEXEC, etc.).  Octal values should
| always be used to set the mode correctly.
|
*/
define('FILE_READ_MODE', 0644);
define('FILE_WRITE_MODE', 0666);
define('DIR_READ_MODE', 0755);
define('DIR_WRITE_MODE', 0777);

/*
|--------------------------------------------------------------------------
| File Stream Modes
|--------------------------------------------------------------------------
|
| These modes are used when working with fopen()/popen()
|
*/

define('FOPEN_READ',							'rb');
define('FOPEN_READ_WRITE',						'r+b');
define('FOPEN_WRITE_CREATE_DESTRUCTIVE',		'wb'); // truncates existing file data, use with care
define('FOPEN_READ_WRITE_CREATE_DESTRUCTIVE',	'w+b'); // truncates existing file data, use with care
define('FOPEN_WRITE_CREATE',					'ab');
define('FOPEN_READ_WRITE_CREATE',				'a+b');
define('FOPEN_WRITE_CREATE_STRICT',				'xb');
define('FOPEN_READ_WRITE_CREATE_STRICT',		'x+b');

/*
 |--------------------------------------------------------------------------
| Constantes del sistema
|--------------------------------------------------------------------------
|
| Constantes utilizados para el sistema
|
*/

define("SUPER_USUARIO", "SPR426");
define("SI", 1);
define("NO", 0);

define("PROTOCOLO_APLICACION", (isset($_SERVER["REQUEST_SCHEME"]) ? $_SERVER["REQUEST_SCHEME"] . "://" : "http://"));
define("NOMBRE_SERVIDOR", (isset($_SERVER["SERVER_NAME"]) ? $_SERVER["SERVER_NAME"] . "/" : ""));
//define("DIRECTORIO_APLICACION",  "qa-pagos/");
define("DIRECTORIO_APLICACION",  "sistema-de-nominas/");
define("DOMINIO_APLICACION", PROTOCOLO_APLICACION . NOMBRE_SERVIDOR . DIRECTORIO_APLICACION);


define("DIRECTORIO_SEPARADOR",  "/");
define("DIRECTORIO_IMAGENES", "assets/images/");
define("DIRECTORIO_IMAGENES_ICON", "assets/images/icon/");
define("DIRECTORIO_ARCHIVOS", "files/");
define("DIRECTORIO_JAVASCRIPT", "assets/js/");
define("DIRECTORIO_HOJAS_ESTILO", "assets/css/");
define("DIRECTORIO_TEMPORAL", "tmp/");
define("DIRECTORIO_CONFIGURACION", "files/configuracion/");
define("DIRECTORIO_MODULOS", "files/modulos/");
define("DIRECTORIO_USUARIOS", "files/usuarios/");
define("DIRECTORIO_ITEMS_MENU", "files/items_menu/");
define("DIRECTORIO_CONFIGURACION_TIMBRADO", "configuracion_timbrado/");
define("DIRECTORIO_EMPRESAS", "empresas/");
define("DIRECTORIO_IMPORTACION_DATOS", "files/importaciondatos/");
define("DIRECTORIO_EMPLEADOS", "files/empleados/");
define("DIRECTORIO_REPORTES_SISTEMA", "files/reportessistema/");

define("LAYOUT_DEFAULT", "layout/default/");
define("LAYOUT_LOGIN", "template_login_view");
define("LAYOUT_SISTEMA", "template_view");

define("AJAX_CONTROLLER", "ajax");

define("LOGO_NOMBRE_DEFAULT", "logo");
define("ICON_IMAGEN_NO_ENCONTRADA", "img-no-encontrada.png");
define("ICON_IMAGEN_USUARIO_DEFAULT", "userss.png");

define("LONGITUD_CONTRASENA_USUARIO", 8);

define("TIPO_ACCION_PRIVADA", 1);
define("TIPO_ACCION_PRIVADA_AJAX", 2);
define("TIPO_ACCION_PUBLICA", 3);
define("TIPO_ACCION_PUBLICA_AJAX", 4);
define("TIPO_ACCION_SECCION", 5);

define("MENU_PRINCIPAL", 1);
define("PANEL_PRINCIPAL", 1);
define("MENU_LINK_DEFAULT", "dashboard/index");
define("MENU_SECCION_USUARIO", 10);

define("MENU_CONFIGURACION", 2);
define("MENU_CONFIGURACION_EMPRESA", 3);
define("MENU_CATALOGOS_COMPENSACION", 4);
define("MENU_CATALOGOS_INCIDENCIAS", 5);
define("MENU_CATALOGOS_TABLASOFICIALES", 6);
define("MENU_CATALOGOS_NOMINA", 7);
define("MENU_CATALOGOS_CLIENTES", 8);
define("MENU_CATALOGOS_TURNOS_CALENDARIOS", 9);
define("MENU_RECURSOS_HUMANOS", 11);
define("MENU_NOMINAS", 12);
define("MENU_PRE_NOMINA", 13);
define("MENU_RECIBO_NOMINA", 14);

define("EMAIL_NUEVO_USUARIO", 1);
define("EMAIL_RESTABLECER_CONTRASENA", 2);
define("EMAIL_ACTUALIZAR_CONTRASENA", 3);

define("LOGO_BLANCO", "assets/images/plantilla/logo-blanco.png");
define("LOGO_NEGRO", "assets/images/plantilla/logo-negro.png");
define("LOGO_FAVICON", "assets/images/plantilla/logo-favicon.png");

define("PDF_FUENTE_CHICA",6);
define("PDF_FUENTE_MEDIANA", 7);
define("PDF_FUENTE_GRANDE", 10);

define("EXPORTAR_COLOR_FILA_UNO", "FFFFFF");
define("EXPORTAR_COLOR_FILA_DOS", "D6E3F7");

define("CONTROLLER_DEFAULT", "dashboard");
define("ACCION_DEFAULT", "index");

define("PAIS_DEFAULT", 1);
define("ESTADO_DEFAULT", 1);
define("CIUDAD_DEFAULT", 1);
define("COLONIA_DEFAULT", 1);


define("IMPORTACION_EXCEPCIONES", 4);
define("IMPORTACION_TIPO_CATALOGO", 1);
define("IMPORTACION_TIPO_EXCEPCION", 2);
define("IMPORTACION_TIPO_EMPRESAS", 2);
define("IMPORTACION_TIPO_IMPORTACION_TIPO_EXCEPCIONADOS", 3);
define("IMPORTACION_TIPO_EMPLEADOS_DATOS_PERSONALES", 4);
define("IMPORTACION_TIPO_EMPLEADOS_DATOS_RECIDENCIA", 5);
define("IMPORTACION_TIPO_PRIMAS_RIESGO", 6);
define("IMPORTACION_TIPO_REGISTROS_PATRONALES", 7);
define("IMPORTACION_TIPO_INCAPACIDADES", 8);

define("IMPORTACION_OPERACION_REGISTRAR_MONTOS", 1);
define("IMPORTACION_OPERACION_SUMAR_MONTOS", 2);
define("IMPORTACION_OPERACION_RESTAR_MONTOS", 3);


define("DIAS_PAGO_PERIODO", 1);
define("DIAS_PAGO_FIJO", 2);

define("NUMBER_FORMAT", 4);
define("NUMBER_FORMAT_PUNTO", ".");
define("NUMBER_FORMAT_COMA", "");

define("DIAS_CALENDARIO", 365);
define("DIAS_MES", 30);
define("DIAS_DE_VACACIONES", 6);
define("UNIDAD", 1);


define("TABLA_NUMERICA_ISR_ART_152_LISR", 3);


define("TABLA_DE_PRESTACIONES_MINIMAS_LEY", 1);
define("TABLA_DE_PRESTACIONES_EMPLEADOS", 2);
define("TABLA_DE_PRESTACIONES_OPERARIOS", 3);

define("PRESTACION_LEY_SUMA_FLOAT_NUEVO", 1);

define("CONFIGURACION_TIPO_SISTEMA", 1);
define("CONFIGURACION_TIPO_TIPONOMINA", 2);
define("CONFIGURACION_TIPO_PRESTACIONES_LEY", 3);
define("CONFIGURACION_TIPO_CUOTASIMSS", 4);
define("CONFIGURACION_TIPO_EMPLEADO", 5);
define("CONFIGURACION_TIPO_PERIODO", 6);
define("CONFIGURACION_TIPO_AHORROSPRESTAMOS", 7);
define("CONFIGURACION_TIPO_FALTASEXTRAS", 8);
define("CONFIGURACION_TIPO_NOMINA", 9);
define("CONFIGURACION_TIPO_AGUINALDO", 10);
define("CONFIGURACION_TIPO_REPARTO_AHORRO", 11);
define("CONFIGURACION_TIPO_REPORTES", 12);
define("CONFIGURACION_TIPO_CALCULO_ISR_ANUAL", 13);

define("ROL_SUPER_USUARIO", 1);
define("ROL_ADMINISTRADOR", 2);
define("ROL_EJECUTIVO", 3);
define("ROL_CLIENTE", 4);
define("ROL_EMPLEADO", 5);

define("CATALOGOFESTIVO_AJUSTE_FECHA_EXACTA", 2);
define("CATALOGOFESTIVO_AJUSTE_PRIMERDIA", 3);
define("CATALOGOFESTIVO_AJUSTE_SEGUNDODIA", 4);
define("CATALOGOFESTIVO_AJUSTE_TERCERDIA", 5);
define("CATALOGOFESTIVO_AJUSTE_CUARTODIA", 6);
define("CATALOGOFESTIVO_AJUSTE_ULTIMODIA", 7);

define("CONTRATO_TREINTA_DIAS", 1);
define("CONTRATO_SESENTA_DIAS", 2);
define("CONTRATO_NOVENTA_DIAS", 3);
define("CONTRATO_INDEFINIDO", 4);


define("TIPO_NOMINA_SEPARACION_TOPE_SEMANAL", 1);
define("TIPO_NOMINA_SEPARACION_TRES_DIARIAS_POR_TRES_DIAS", 2);

define("FRECUENCIA_TIPO_SALARIO", 3);
define("FRECUENCIA_TIPO_NOMINA", 1);
define("FRECUENCIA_TIPO_PRESTACIONES", 2);
define("FRECUENCIA_DIARIO", 21);
define("FRECUENCIA_SEMANAL", 1);
define("FRECUENCIA_DECENAL", 2);
define("FRECUENCIA_CATORCENAL", 3);
define("FRECUENCIA_QUINCENAL", 4);
define("FRECUENCIA_MENSUAL", 5);

define("TURNO_TIPO_FRECUENCIA_SEMANAL", 1);
define("TURNO_TIPO_FRECUENCIA_QUINCENAL", 2);

define("EMPLEADO_EMPRESA_INTERNA", 1);
define("EMPLEADO_CLIENTE", 2);
define("EMPLEADO_TRABAJADOR", 3);
define("EMPLEADO_ESTATUS_ALTA", 1);
define("EMPLEADO_ESTATUS_BAJA", 2);

define("EMPLEADO_FORMA_EDITAR_TIPO_FORMA_PAGO", 1);
define("EMPLEADO_FORMA_EDITAR_TIPO_EDITAR_EMPLEADO", 2);

define("ANO_VENCIMIENTO", 100);
define("AVISOS_BUSCAR_USUARIO", 1);
define("AVISOS_BUSCAR_NIVEL_ACCESO", 2);
define("AVISOS_BUSCAR_TODOS", 3);
define("AVISOS_ESTATUS_ENVIADO", 1);
define("AVISOS_ESTATUS_LEIDO", 2);
define("AVISOS_ESTATUS_BORRADOR", 3);
define("AVISOS_ESTATUS_NO_LEIDO", 4);

define("INFONAVIT_TIPO_RETENCION_PORCENTAJE", 1);
define("INFONAVIT_TIPO_RETENCION_CUOTAFIJA", 2);
define("INFONAVIT_TIPO_RETENCION_VSMG", 3);
define("INFONAVIT_MOVIMIENTO_TIPO_INICIO", 1);
define("INFONAVIT_MOVIMIENTO_TIPO_MODIFICACION", 2);
define("INFONAVIT_MOVIMIENTO_TIPO_SUSPENCION", 3);
define("INFONAVIT_MOVIMIENTO_TIPO_REACTIVACION", 4);
define("INFONAVIT_MOVIMIENTO_TIPO_FINALIZADO", 5);
define("INFONAVIT_ESTATUS_CREDITO_ACTIVO", 1);
define("INFONAVIT_ESTATUS_CREDITO_SUSPENDIDO", 2);
define("INFONAVIT_ACCION_INSERTAR", 1);
define("INFONAVIT_ACCION_ACTUALIZAR", 2);
define("INFONAVIT_ACCION_REACTIVAR", 3);
define("NUMERO_BISMESTRE", 2);

define("PAGINACION_PEAR_PAGE", 30);
define("PAGINACION_NUM_LINKS", 3);

define("FOLIOS_FISCALES_NUMERO_INICIAL_DEFALT", 1);

define("AHORROPRESTAMO_CATEGORIA_AHORRO", 1);
define("AHORROPRESTAMO_CATEGORIA_PRESTAMO", 2);
define("AHORROPRESTAMO_CATEGORIA_DESCUENTO", 3);
define("AHORROPRESTAMO_CATEGORIA_FONACOT", 4);

define("AHORROPRESTAMO_DESCONTAR_MONTO_FIJO", 1);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_AHORRO_FONDO_DE_AHORRO", 1);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_AHORRO_CAJA_DE_AHORRO", 2);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_DESCUENTO_EQUIPO_TRABAJO", 3);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_DESCUENTO_UNIFORMES", 4);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_DESCUENTO_PRESTAMO", 5);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_CREDITOPENSION_OTROS_DESCUENTOS", 6);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_CREDITOPENSION_PENSION_ALIMENTICIA", 7);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_CREDITOPENSION_REEMBOLSOS", 8);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_CREDITOFONACOT", 9);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_DESCUENTO_PRESTAMO_FINANCIERA", 10);
define("AHORROPRESTAMO_TIPOAHORROPRESTAMO_DESCUENTO_PRESTAMO_CAJA_AHORRO", 11);

define("AHORROPRESTAMO_ESTATUS_ACTIVO", 1);
define("AHORROPRESTAMO_ESTATUS_CANCELADO", 2);
define("AHORROPRESTAMO_ESTATUS_SALDADO", 3);

define("ESTADOCUENTA_TIPO_MOVIMIENTO_CARGO", 1);
define("ESTADOCUENTA_TIPO_MOVIMIENTO_ABONO", 2);


define("FORMA_DE_PAGO_DEPOSITO", 1);
define("FORMA_DE_PAGO_EFECTIVO", 2);
define("FORMA_DE_PAGO_CHEQUE", 3);
define("FORMA_DE_PAGO_OTRA", 4);

define("PERIODO_ESTATUS_NUEVA", 1);
define("PERIODO_ESTATUS_NOMINA_PARCIAL", 2);
define("PERIODO_ESTATUS_NOMINA_TOTAL", 3);
define("PERIODO_ESTATUS_NOMINA_AFECTADA", 4);
define("PERIODO_TIPO_ORDINARIO", 1);
define("PERIODO_TIPO_ESPECIAL", 2);

define("PERIODO_PROCESO_TIPO_NOMINA", 1);
define("PERIODO_PROCESO_TIPO_AGUINALDO", 2);
define("PERIODO_PROCESO_TIPO_AHORROPRESTAMOS", 3);
define("PERIODO_PROCESO_TIPO_REPARTO_AHORRO", 4);

define("EXCEPCION_TIPO_DIAS_AJUSTE", 1);
define("EXCEPCION_TIPO_DIAS_Y_HORAS", 2);
define("EXCEPCION_TIPO_MONTOS", 3);

define("KARDEX_MOTIVO_ALTA_EMPLEADO", 1);
define("KARDEX_MOTIVO_BAJA_EMPLEADO", 1);

define("KARDEX_TIPO_MOTIVO_ALTA", 1);
define("KARDEX_TIPO_MOTIVO_BAJA", 2);
define("KARDEX_TIPO_MOTIVO_SALARIO", 18);
define("KARDEX_TIPO_MOTIVO_PUESTO", 22);
define("KARDEX_TIPO_MOTIVO_AREA", 6);
define("KARDEX_TIPO_MOTIVO_DEPARTAMENTO", 5);
define("KARDEX_TIPO_MOTIVO_CONTRATO", 3);
define("KARDEX_TIPO_MOTIVO_TIPO_DE_NOMINA", 14);
define("KARDEX_TIPO_MOTIVO_TURNO", 20);
define("KARDEX_TIPO_MOTIVO_TABLA_PRESTACIONES_LEY", 17);
define("KARDEX_TIPO_MOTIVO_UBICACION", 21);
define("KARDEX_TIPO_MOTIVO_CLIENTE", 23);
define("KARDEX_TIPO_MOTIVO_REGISTRO_PATRONAL", 24);

define("KARDEX_ALTA_DE_EMPLEADO", 1);
define("KARDEX_CAMBIO_DE_SALARIO", 2);
define("KARDEX_CAMBIO_DE_PUESTO", 3);
define("KARDEX_CAMBIO_DE_AREA_UBICACION_DEPARTAMENTO", 4);
define("KARDEX_CAMBIO_DE_CONTRATACION", 5);
define("KARDEX_CAMBIO_DE_TIPO_DE_NOMINA", 6);
define("KARDEX_CAMBIO_DE_TIPO_DE_TURNO", 7);
define("KARDEX_CAMBIO_DE_TIPO_NOMINA", 8);
define("KARDEX_CAMBIO_DE_CLIENTE", 9);

define("KARDEX_CAMBIO_CAMPO_PUESTO", 'idPuesto');
define("KARDEX_CAMBIO_CAMPO_CLIENTE", 'idCliente');
define("KARDEX_CAMBIO_CAMPO_TIPO_DE_NOMINA", 'idTipoNomina');
define("KARDEX_CAMBIO_CAMPO_DEPARTAMENTO", 'idDepartamento');

define("CONCEPTO_LISTADO_PRENOMINA", 1);
define("CONCEPTO_LISTADO_NOMINA", 2);
define("CONCEPTO_LISTADO_PERCEPCIONES", 3);
define("CONCEPTO_LISTADO_DEDUCCIONES", 4);
define("CONCEPTO_LISTADO_ESTRATEGIA_PS", 5);
define("CONCEPTO_LISTADO_IMPUESTO_ESTATAL", 6);
define("CONCEPTO_LISTADO_RASTREAR_CALCULO", 9);
define("CONCEPTO_LISTADO_AFECTAR_NOMINA", 10);
define("CONCEPTO_LISTADO_MONTOS_EXCENTO", 13);

define("CONCEPTO_LISTADO_PESTANA_PS", 18);

define("CONCEPTO_MOSTRAR_LISTADO_NO_MOSTRAR", 1);
define("CONCEPTO_MOSTRAR_LISTADO_SOLO_GRAN_TOTAL", 2);
define("CONCEPTO_MOSTRAR_LISTADO_SUBTOTAL_Y_TOTAL", 3);
define("CONCEPTO_LISTADO_PESTANA_DETALLE_Y_TOTAL", 4);

define("CALCULO_ISR_ANUAL_CONCEPTOS_SUELDO_Y_SALARIOS", 14);
define("CALCULO_ISR_ANUAL_CONCEPTOS_SUELDO_Y_SALARIOS_EXCENTO", 16);
define("CALCULO_ISR_ANUAL_CONCEPTOS_OTROS_INGRESOS_SALARIOS", 15);
define("CALCULO_ISR_ANUAL_CONCEPTOS_OTROS_INGRESOS_SALARIOS_EXCENTO", 17);

define("CONCEPTO_DIAS_AJUSTE", 8);
define("CONCEPTO_HORAS_EXTRAS_DOBLES", 3);
define("CONCEPTO_HORAS_EXTRAS_TRIPLES", 4);
define("CONCEPTO_FESTIVO_TRABAJADO", 5);
define("CONCEPTO_DESCANSO_TRABAJADO", 6);
define("CONCEPTO_HORAS_DESCONTAR", 71);
define("CONCEPTO_FONDO_AHORRO", 35);
define("CONCEPTO_ENTREGA_FONDO_AHORRO", 52);
define("CONCEPTO_ENTREGA_CAJA_AHORRO", 53);
define("CONCEPTO_CAJA_AHORRO", 34);
define("CONCEPTO_CREDITO_INFONAVIT", 39);
define("CONCEPTO_CREDITO_FONACOT", 40);

define("CONCEPTO_DESCUENTO_EQUIPO_TRABAJO", 45);

define("CONCEPTO_DESCUENTO_EMPLEADO", 63);
define("CONCEPTO_DESCUENTO_TIENDA", 64);
define("CONCEPTO_DESCUENTO_UNIFORME", 65);
define("CONCEPTO_DESCUENTO_EQUIPO", 66);
define("CONCEPTO_DESCUENTO_PRESTAMO_CLIENTE", 67);
define("CONCEPTO_DESCUENTO_AHORRO", 68);
define("CONCEPTO_DESCUENTO_COLEGIATURA", 69);
define("CONCEPTO_DESCUENTO_CURSO", 70);

define("CONCEPTO_OTROS_DESCUENTOS", 46);

define("CONCEPTO_CARGA_SOCIAL", 122);

define("CONCEPTO_PRESTAMO", 61);
define("CONCEPTO_PRESTAMO_CAJA_AHORRO", 36);
define("CONCEPTO_PRESTAMO_FINANCIERA", 72);
define("CONCEPTO_PENSION_ALIMENTICIA", 41);
define("CONCEPTO_REEMBOLSOS", 62);
define("CONCEPTO_DESCUENTO_UNIFORMES", 44);
define("CONCEPTO_COMISIONES", 21);
define("CONCEPTO_REPARTO_UTILIDADES_PTU", 14);
define("CONCEPTO_AGUINALDO", 13);
define("CONCEPTO_OTRAS_PERCEPCIONES", 10);
define("CONCEPTO_OTRAS_PERCEPCIONES_DE_SALARIO", 59);
define("CONCEPTO_INCAPACIDAD", 14);
define("CONCEPTO_VACACIONES", 11);
define("CONCEPTO_PRIMA_VACACIONAL", 12);
define("CONCEPTO_PRIMA_DOMINICAL", 7);
define("CONCEPTO_SALARIO_ORDINARIO", 1);
define("CONCEPTO_SEPTIMO_DIA", 2);
define("CONCEPTO_ISR", 31);
define("CONCEPTO_REEMBOLSO_ISR_A_FAVOR", 42);
define("CONCEPTO_DIFERENCIA_ISR_A_CARGO", 43);
define("CONCEPTO_IMSS", 32);
define("CONCEPTO_IMSS_EMPRESA", 74);
define("CONCEPTO_IMSS_RETIRO", 75);
define("CONCEPTO_IMPUESTO_ESTATAL", 77);
define("CONCEPTO_EXCENTO_HORAS_EXTRAS_DOBLES", 96);
define("CONCEPTO_EXCENTO_FESTIVO_TRABAJADO", 97);
define("CONCEPTO_EXCENTO_DESCANSO_TRABAJADO", 98);
define("CONCEPTO_EXCENTO_PRIMA_DOMINICAL", 99);
define("CONCEPTO_EXCENTO_DE_PRIMA_VACACIONAL", 100);
define("CONCEPTO_EXCENTO_DE_AGUINALDO", 101);
define("CONCEPTO_EXCENTO_DE_PTU", 102);
define("CONCEPTO_EXCENTO_DE_PREVISION_SOCIAL", 103);
define("CONCEPTO_EXCENTO_OTROS_EXCENTOS_PERIODICOS", 104);
define("CONCEPTO_DIAS_VACACIONES_A_PAGAR", 105);
define("CONCEPTO_DIAS_PRIMA_VACACIONAL", 106);
define("CONCEPTO_DIAS_AGUINALDO_PAGAR", 107);
define("CONCEPTO_HORAS_EXTRAS_DOBLES_PAGAR", 108);
define("CONCEPTO_HORAS_EXTRAS_TRIPLES_PAGAR", 109);
define("CONCEPTO_HORAS_FESTIVO_TRABAJADO_A_PAGAR_PAGAR", 110);
define("CONCEPTO_DIAS_FESTIVO_TRABAJADO", 113);
define("CONCEPTO_DIAS_DESCANSO_TRABAJADO", 114);
define("CONCEPTO_DIAS_DE_AJUSTE_A_PAGAR", 112);
define("CONCEPTO_GRATIFICACION_ANUAL", 30);
define("CONCEPTO_EXCENTO_GRATIFICACION_ANUAL", 115);

define("CONCEPTO_FALTAS_INCAPCIDAD", 124);
define("CONCEPTO_FALTAS_VACACIONES", 125);

define("CONCEPTO_AJUSTE_COMISION", 118);
define("CONCEPTO_AJUSTE_COMISION_EMPLEADO", 119);
define("CONCEPTO_AJUSTE_COMISION_CLIENTE", 120);


define("CONCEPTO_IMSS_OBRERA_SEGURO_DE_ENFERMEDAD_Y_MATERNIDAD", 92);
define("CONCEPTO_IMSS_OBRERA_CUOTA_ADICIONAL_PRESTACIONES_ESPECIE", 89);
define("CONCEPTO_IMSS_OBRERA_CUOTA_JUBILADOS_Y_BENEFICIARIOS_PRESTACIONES_ESPECIE", 90);
define("CONCEPTO_IMSS_OBRERA_CUOTA_PRESTACIONES_DINERO", 91);
define("CONCEPTO_IMSS_OBRERA_SEGURO_INVALIDEZ_Y_VIDA", 93);
define("CONCEPTO_IMSS_OBRERA_SEGURO_CESANTIA_EDAD_AVANZADA_Y_VEJEZ", 94);

define("CONCEPTO_IMSS_PATRONAL_SEGURO_DE_RIESGO_DE_TRABAJO",79);
define("CONCEPTO_IMSS_PATRONAL_SEGURO_ENFERMEDAD_Y_MATERNIDAD", 80);
define("CONCEPTO_IMSS_PATRONAL_CUOTA_FIJA_PRESTACIONES_ESPECIE", 84);
define("CONCEPTO_IMSS_PATRONAL_CUOTA_ADICIONAL_PRESTACIONES_ESPECIE", 85);
define("CONCEPTO_IMSS_PATRONAL_CUOTA_JUBILADOS_Y_BENEFICIARIOS_PRESTACIONES_ESPECIE", 86);
define("CONCEPTO_IMSS_PATRONAL_CUOTA_PRESTACIONES_DINERO", 87);
define("CONCEPTO_IMSS_PATRONAL_SEGURO_DE_INVALIDEZ_Y_VIDA", 81);
define("CONCEPTO_IMSS_PATRONAL_SEGURO_CESANTIA_EDAD_AVANZADA_Y_VEJEZ", 82);
define("CONCEPTO_IMSS_PATRONAL_CUOTA_CESANTIA_EDAD_AVANZADA_Y_VEJEZ", 88);
define("CONCEPTO_IMSS_PATRONAL_SEGURO_GUARDERIA_Y_PRESTACIONES_SOCIALES", 83);
define("CONCEPTO_IMSS_PATRONAL_CUOTA_RETIRO",95);

define("FONDO_DE_AHORRO_ENTREGAR_MONTO_FIJO", 1);
define("FONDO_DE_AHORRO_ENTREGAR_POR_FORMULA", 2);

define("CONCEPTO_PPSE_EJECUTIVA", 121);
define("CONCEPTO_INFONAVIT_EMPRESA", 76);
define("CONCEPTO_SUBCIDIO_EMPLEADO", 33);
define("CONCEPTO_PPSE_EDUCACION", 73);
define("CONCEPTO_PPSE_CULTURA", 55);
define("CONCEPTO_PPSE_DEPORTE_Y_RECREACION", 56);
define("CONCEPTO_PPSE_SALUD_Y_VIDA", 57);
define("CONCEPTO_PPSE_RETIRO_Y_AHORRO", 58);
define("CONCEPTO_SEGURO_DE_GASTOS_DE_VIVIENDA", 47);
define("REFERENCIA_SEGURO_DE_GASTOS_DE_VIVIENDA", 2);

define("CONCEPTO_NUMERO_INCAPACIDAD", 14);
define("CONCEPTO_NUMERO_VACACIONES", 21);
define("CONCEPTO_NUMERO_PRIMA_VACACIONAL", 22);
define("CONCEPTO_NUMERO_SALARIO_ORDINARIO", 1);

define("CONCEPTOS_TIPO_TRATAMIENTO_ISR", 1);
define("CONCEPTOS_TIPO_TRATAMIENTO_IMSS", 2);
define("CONCEPTOS_TRATAMIENTO_ISR_EXENTO_AL_CIEN", 2);

define("CONCEPTOS_TIPO_PERCEPCION", 1);
define("CONCEPTOS_TIPO_DEDUCCION", 2);
define("CONCEPTOS_TIPO_OBLIGATORIOS", 5);
define("CONCEPTOS_TIPO_CALCULO", 6);

define("CONCEPTOS_TIMBRADO_TIPO_MONTO_POSITIVO", 1);
define("CONCEPTOS_TIMBRADO_TIPO_MONTO_NEGATOVO", 2);

define("CONCEPTOS_TRATAMIENTO_CONCEPTO_DIAS", 1);
define("CONCEPTOS_TRATAMIENTO_CONCEPTO_HORAS", 2);
define("CONCEPTOS_TRATAMIENTO_CONCEPTO_MONTO", 3);

define("FALTASEXTRAS_TIPO_FALTA", 1);
define("FALTASEXTRAS_TIPO_EXTRAS", 2);
define("FALTASEXTRAS_TIPO_ORDINARIAS", 3);
define("FALTASEXTRAS_TIPO_RETARDO", 4);
define("FALTASEXTRAS_TIPO_FESTIVO", 5);

define("FALTASEXTRAS_MOTIVO_PAGO_FESTIVO", 5);

define("VACACIONES_TIPO_SALDO_DIAS_GOZAR",1);
define("VACACIONES_TIPO_SALDO_DIAS_PAGAR",2);
define("VACACIONES_TIPO_SALDO_PRIMA_PAGAR",3);
define("VACACIONES_ESTATUS_PENDIENTE_PAGAR",1);
define("VACACIONES_ESTATUS_PAGADAS",1);

define("INCAPACIDAD_ACCIDENTE_DE_TRABAJO",1);
define("INCAPACIDAD_ENFERMEDAD_GENERAL",2);
define("INCAPACIDAD_ENFERMEDAD_DE_TRABAJO",3);
define("INCAPACIDAD_PRE_MATERNAL",4);
define("INCAPACIDAD_MATERNAL_ENLACE",5);
define("INCAPACIDAD_POST_MATERNAL",6);
define("INCAPACIDAD_ACCIDENTE_DE_TRAYECTO",7);

define("NOMINA_ESTATUS_NUEVA", 1);
define("NOMINA_ESTATUS_NOMINA_TOTAL", 3);
define("NOMINA_ESTATUS_NOMINA_AFECTADA_TOTAL", 4);
define("NOMINA_ESTATUS_TIMBRADA_PARCIAL", 5);
define("NOMINA_ESTATUS_TIMBRADA_TOTAL", 6);

define("PERMISO_TIPO_CON_GOCE_DE_SUELDO", 5);
define("PERMISO_TIPO_SIN_GOCE_DE_SUELDO", 6);

define("TABLA_NUMERICA_ARTICULO_92_LISR", 1);
define("TABLA_NUMERICA_SUBCIDIO_EMPLEADO", 2);
define("TABLA_NUMERICA_ARTICULO_152_LISR", 3);

define("NOMINA_PESTANA_INCIDENCIAS", "Incidencias");
define("NOMINA_PESTANA_HORAS_DIAS", "Capturar horas / dias");
define("NOMINA_PESTANA_DEDUCCIONES", "Capturar deducciones");

define("NOMINA_PESTANA_TIPO_REVISAR_EMPLEADOS", 0);
define("NOMINA_PESTANA_TIPO_INCIDENCIAS", 1);
define("NOMINA_PESTANA_TIPO_HORAS_DIAS", 2);
define("NOMINA_PESTANA_TIPO_PERCEPCIONES", 3);
define("NOMINA_PESTANA_TIPO_PREVISION_SOCIAL", 4);
define("NOMINA_PESTANA_TIPO_DESCUENTOS", 5);
define("NOMINA_PESTANA_TIPO_AUTORIZAR_MONTOS", 6);

define("NOMINA_TIPO_DESCUENTO_CREDITO_INFONAVIT",1);
define("NOMINA_TIPO_DESCUENTO_AHORRO_PRESTAMO",2);

define("RECIBONOMINA_FILTRO_GRAVABLE", 1);
define("RECIBONOMINA_FILTRO_PS", 2);
define("RECIBONOMINA_FILTRO_EXCEPCION_NOMINA", 3);
define("RECIBONOMINA_FILTRO_EXCEPCION_PRENOMINA", 4);

define("RECIBONOMINA_VERTICAL", 1);
define("RECIBONOMINA_HORIZONTAL", 2);

define("RECIBONOMINA_IMPRIMIR_LISTADO", 1);
define("RECIBONOMINA_IMPRIMIR_EMPLEADO", 2);

define("RECIBONOMINA_FILTRO_TODOS", 1);
define("RECIBONOMINA_FILTRO_ACTIVO", 2);
define("RECIBONOMINA_FILTRO_BAJA", 4);
define("RECIBONOMINA_FILTRO_LISTA", 3);


define("REDONDEAR_DECIMALES", 2);

define("BANCOS_BANAMEX", 1);
define("BANCOS_BANCOMER", 2);
define("BANCOS_BANORTE", 3);
define("BANCOS_HSBC", 4);
define("BANCOS_SATANDER", 5);
define("BANCOS_BANREGIO", 6);
define("BANCOS_AFIRME", 7);
define("BANCOS_AZTECA", 8);
define("BANCOS_BAJIO", 9);
define("BANCOS_SCOTIABANK", 10);



define("BANCOS_BANAMEX_ARCHIVO_EXPORTAR", "banamex");
define("BANCOS_BANAMEX_LAYOUT_D", 1);

define("BANCOS_BANAMEX_LAYOUT_D_REGISTRO_DE_CONTROL", 1);
define("BANCOS_BANAMEX_LAYOUT_D_CLIENTE_LONGITUD", 12);
define("BANCOS_BANAMEX_LAYOUT_D_SECUENCIAL_LONGITUD", 4);
define("BANCOS_BANAMEX_LAYOUT_D_NOMBRE_EMPRESA_LONGITUD", 36);
define("BANCOS_BANAMEX_LAYOUT_D_DESCRIPCION_ARCHIVO_LONGITUD", 20);
define("BANCOS_BANAMEX_LAYOUT_D_NATURALEZA_ARCHIVO", 15);
define("BANCOS_BANAMEX_LAYOUT_D_VERSION_LAYOUT", "D");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_CARGO", "01");

define("BANCOS_BANAMEX_LAYOUT_D_REGISTRO_GLOBAL", 2);
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_OPERACION", 1);
define("BANCOS_BANAMEX_LAYOUT_D_CLAVE_MONEDA", "001");
define("BANCOS_BANAMEX_LAYOUT_D_DECIMALES_IMPORTE_LONGITUD", 2);
define("BANCOS_BANAMEX_LAYOUT_D_IMPORTE_A_CARGAR_LONGITUD", 18);
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_CUENTA", "01");
define("BANCOS_BANAMEX_LAYOUT_D_NUMERO_DE_CUENTA_LONGITUD", 20);
define("BANCOS_BANAMEX_LAYOUT_D_NUMERO_TOTAL_DE_ABONOS", 6);

define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_REGISTRO_DETALLE", 3);
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_OPERACION_ABONO", 0);

define("BANCOS_BANAMEX_LAYOUT_D_METODO_DE_PAGO_BANAMEX", "001");
define("BANCOS_BANAMEX_LAYOUT_D_METODO_DE_PAGO_INTERBANCARIO", "002");
define("BANCOS_BANAMEX_LAYOUT_D_METODO_DE_PAGO_ORDEN_DE_PAGO", "003");

define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_NOMINA", "01");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_AGUINALDO", "51");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_BONO", "52");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_GASTOS_MEDICOS", "53");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_PENSION", "54");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_REEMBOLSOS_DE_GASTOS", "55");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_VIATICOS", "56");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_GASTOS_DE_REPRESENTACION", "57");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_GASOLINA", "58");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_PAGO_ABONO_LIQUIDACION_DE_GASTOS_DE_VIAJE", "59");

define("BANCOS_BANAMEX_LAYOUT_D_CLAVE_DE_MONEDA", "001");
define("BANCOS_BANAMEX_LAYOUT_D_IMPORTE_LONGUITUD", "18");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_CUENTA_DE_ABONO_CHEQUES", "01");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_CUENTA_DE_ABONO_PLASTICOS", "03");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_CUENTA_DE_ABONO_ORDEN_DE_PAGO", "04");
define("BANCOS_BANAMEX_LAYOUT_D_TIPO_DE_CUENTA_DE_ABONO_CLABE", "40");

define("BANCOS_BANAMEX_LAYOUT_D_NUMERO_DE_CUENTA_ABONO_LONGITUD", 20);
define("BANCOS_BANAMEX_LAYOUT_D_REFERENCIA_DEL_PAGO_LONGITUD", 16);
define("BANCOS_BANAMEX_LAYOUT_D_BENEFICIARIO_LONGITUD", 55);
define("BANCOS_BANAMEX_LAYOUT_D_REFERENCIA_1", "REFERENCIA 1");
define("BANCOS_BANAMEX_LAYOUT_D_REFERENCIA_2", "REFERENCIA 2");
define("BANCOS_BANAMEX_LAYOUT_D_REFERENCIA_3", "REFERENCIA 3");
define("BANCOS_BANAMEX_LAYOUT_D_REFERENCIA_4", "REFERENCIA 4");
define("BANCOS_BANAMEX_LAYOUT_D_REFERENCIA_LONGITUD", 35);
define("BANCOS_BANAMEX_LAYOUT_D_CLAVE_DE_BANCO_LONGITUD", 4);
define("BANCOS_BANAMEX_LAYOUT_D_PLAZO_MISMO_DIA", "00");
define("BANCOS_BANAMEX_LAYOUT_D_PLAZO_24_HORAS", "24");
define("BANCOS_BANAMEX_LAYOUT_D_PLAZO_PAGOS_RESTANTES", "00");
define("BANCOS_BANAMEX_LAYOUT_D_RFC_LONGITUD", 14);
define("BANCOS_BANAMEX_LAYOUT_D_IVA_LONGITUD", 8);
define("BANCOS_BANAMEX_LAYOUT_D_PARA_FUTURO_USO_1", 80);
define("BANCOS_BANAMEX_LAYOUT_D_PARA_FUTURO_USO_2", 50);

define("BANCOS_BANAMEX_LAYOUT_D_TIPO_REGISTRO_CONTROL_FINAL", 4);
define("BANCOS_BANAMEX_LAYOUT_D_NUMERO_DE_ABONOS_LONGITUD", 6);
define("BANCOS_BANAMEX_LAYOUT_D_IMPORTE_TOTAL_ABONOS_LONGITUD", 10);
define("BANCOS_BANAMEX_LAYOUT_D_NUMERO_DE_CARGOS_LONGITUD", 6);
define("BANCOS_BANAMEX_LAYOUT_D_IMPORTE_TOTAL_DE_CARGOS_LONGITUD", 18);


define("BANCOS_BANAMEX_LAYOUT_B", 2);


define("BANCOS_BANAMEX_LAYOUT_B_CAMPOS", "idCliente, iSecuencial, cDescripcion, cCuentaCargo, dtFechaPago, cNaturaleza, cInstrucciones, iSucursal");
define("BANCOS_BANAMEX_LAYOUT_CD_CAMPOS", "idCliente, iSecuencial, cDescripcion, cCuentaCargo, dtFechaPago");



define("BANCOS_BANAMEX_LAYOUT_B_REGISTRO_DE_CONTROL", 1);
define("BANCOS_BANAMEX_LAYOUT_B_CLIENTE_LONGITUD", 12);
define("BANCOS_BANAMEX_LAYOUT_B_SECUENCIAL_LONGITUD", 4);
define("BANCOS_BANAMEX_LAYOUT_B_NOMBRE_EMPRESA_LONGITUD", 36);
define("BANCOS_BANAMEX_LAYOUT_B_DESCRIPCION_ARCHIVO_LONGITUD", 20);
define("BANCOS_BANAMEX_LAYOUT_B_NATURALEZA_ARCHIVO_PAGO_NOMINA", "00");
define("BANCOS_BANAMEX_LAYOUT_B_NATURALEZA_ARCHIVO_COBROS", "04");
define("BANCOS_BANAMEX_LAYOUT_B_NATURALEZA_ARCHIVO_PAGO_MATICO", "05");
define("BANCOS_BANAMEX_LAYOUT_B_NATURALEZA_ARCHIVO_PAGO_A_PROVEDORES", "06");

define("BANCOS_BANAMEX_LAYOUT_B_INSTRUCCIONES_ORDENES_DE_PAGO", "40");
define("BANCOS_BANAMEX_LAYOUT_B_VERSION_LAYOUT", "B");
define("BANCOS_BANAMEX_LAYOUT_B_VOLUMEN", 0);
define("BANCOS_BANAMEX_LAYOUT_B_CARACTERISTICAS_ARCHIVO_MODIFICABLE", 0);
define("BANCOS_BANAMEX_LAYOUT_B_CARACTERISTICAS_ARCHIVO_SOLO_LECTURA", 1);

define("BANCOS_BANAMEX_LAYOUT_B_REGISTRO_GLOBAL", 2);
define("BANCOS_BANAMEX_LAYOUT_B_TIPO_DE_OPERACION_ABONO", 0);
define("BANCOS_BANAMEX_LAYOUT_B_TIPO_DE_OPERACION_CARGO", 1);
define("BANCOS_BANAMEX_LAYOUT_B_CLAVE_MONEDA", "001");
define("BANCOS_BANAMEX_LAYOUT_B_IMPORTE_A_CARGAR_LONGITUD", 18);
define("BANCOS_BANAMEX_LAYOUT_B_TIPO_DE_CUENTA", "01");
define("BANCOS_BANAMEX_LAYOUT_B_NUMERO_SUCURSAL_LONGITUD", 4);
define("BANCOS_BANAMEX_LAYOUT_B_NUMERO_DE_CUENTA_LONGITUD", 20);
define("BANCOS_BANAMEX_LAYOUT_B_ESPACIOS_EN_BLANCO", 20);


define("BANCOS_BANAMEX_LAYOUT_B_REGISTRO_MOTIVOS_INDIVIDUALES", 3);
define("BANCOS_BANAMEX_LAYOUT_B_TIPO_OPERACION_INDIVIDUALES", 0);

define("BANCOS_BANAMEX_LAYOUT_B_TIPO_DE_CUENTA_CHEQUES", "01");
define("BANCOS_BANAMEX_LAYOUT_B_TIPO_DE_CUENTA_PLASTICOS", "03");
define("BANCOS_BANAMEX_LAYOUT_B_TIPO_DE_CUENTA_ORDEN_DE_PAGO", "04");
define("BANCOS_BANAMEX_LAYOUT_B_TIPO_DE_CUENTA_INTERBANCOS", "08");
define("BANCOS_BANAMEX_LAYOUT_B_TIPO_DE_CUENTA_CONCENTRADORA", "15");

define("BANCOS_BANAMEX_LAYOUT_B_REFERENCIA_DE_LA_OPERACION_LONGITUD", "40");
define("BANCOS_BANAMEX_LAYOUT_B_BENEFICIARIO_LONGITUD", "55");
define("BANCOS_BANAMEX_LAYOUT_B_DESCRIPCION_LONGITUD", "24");
define("BANCOS_BANAMEX_LAYOUT_B_CLAVE_DE_ESTADO_LONGITUD", "02");
define("BANCOS_BANAMEX_LAYOUT_B_CLAVE_DE_CIUDAD_LONGITUD", "04");
define("BANCOS_BANAMEX_LAYOUT_B_CLAVE_DE_BANCO_LONGITUD", "04");

define("BANCOS_BANAMEX_LAYOUT_B_REGISTRO_TOTALES", 4);
define("BANCOS_BANAMEX_LAYOUT_B_NUMERO_DE_ABONOS_LONGITUD", 6);
define("BANCOS_BANAMEX_LAYOUT_B_NUMERO_DE_CARGOS", "000001");


define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC", 3);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_VERSION", "C");

define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_TIPO_REGISTRO_CONTROL", "1");
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_NUMERO_IDENTIFICACION_CLIENTE_LONGITUD", 12);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_SECUECIAL_ARCHIVO_LONGITUD", 4);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_NOMBRE_EMPRESA_LONGITUD", 36);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_DESCRIPCION_ARCHIVO_LONGITUD", 20);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_NATURALEZA_ARCHIVO_PAGO_NOMINA_PAGOMATICO", "05");
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_NATURALEZA_ARCHIVO_INTERBANCARIO", "07");
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_INSTRUCCIONES_ORDEN_PAGO_LONGITUD", 40);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_VOLUMEN_MODIFICABLE", 0);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_CARACTERISTICAS_DEL_ARCHIVO", 0);


define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_TIPO_REGISTRO_GLOBAL", 2);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_TIPO_OPERACION_CARGO", 1);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_CLAVE_MONEDA", "001");
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_IMPORTE_ABONAR_LONGITUD", 18);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_TIPO_CUENTA_CHEQUES", "01");
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_NUMERO_SUCURSAL_LONGITUD", 04);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_NUMERO_CUENTA_LONGITUD", 20);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_ESPACION_EN_BLANCO_LONGITUD", 20);

define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_TIPO_MOVIMIENTO_REGISTROS_INDIVIDUALES", 3);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_TIPO_OPERACION_INDIVIDUAL_ABONO", 0);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_IMPORTE_LONGITUD", 18);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_REFERENCIA_DE_LA_OPERACION_TEF", 40);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_BENEFICIARIO_LONGITUD", 55);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_INSTRUCCIONES_LONGITUD", 40);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_DESCRIPCION_TEF_LONGITUD", 24);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_CLAVE_BANCO_LONGITUD", 4);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_REFERENCIA_BAJO_VALOR_LONGITUD", 7);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_PLAZO_MISMO_DIA", "00");

define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_TIPO_REGISTRO_CONTROL_FINAL", 4);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_NUMERO_DE_ABONOS_LONGITUD", 6);
define("BANCOS_BANAMEX_LAYOUT_C_PAGOMATIC_NUMERO_DE_CARGOS_LONGITUD", 6);


define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA", 4);
define("BANCOS_BANORTE_ARCHIVO_EXPORTAR", "banorte");
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_TIPO_REGISTRO", 'H');
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_CLAVE_DE_SERVICIO", 'NE');
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_CONSECUTIVO_LONGITUD", 2);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_NUMERO_TOTAL_DE_REGISTROS_ENVIADOS_LONGITUD", 6);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_IMPORTE_TOTAL_DE_REGISTROS_ENVIADOS_LONGITUD", 15);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_NUMERO_TOTAL_DE_ALTAS_LONGITUD", 6);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_IMPORTE_TOTAL_DE_ALTAS_LONGITUD", 15);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_NUMERO_TOTAL_DE_BAJAS_LONGITUD", 6);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_IMPORTE_TOTAL_DE_BAJAS_LONGITUD", 15);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_NUMERO_TOTAL_DE_CUENTAS_A_VERIFICAR", 6);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_ACCION", 0);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_FILTER_ESPACIOS_EN_BLANCO", 77);

define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_TIPO_REGISTRO_DETALLE", "D");
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_NUMERO_EMPLEADO_LONGITUD", 10);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_REFERENCIA_SERVICIO_LONGITUD", 40);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_REFERENCIA_LEYENDA_DEL_ORDENANTE_LONGITUD", 40);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_IMPORTE_A_PAGAR_LONGITUD", 15);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_NUMERO_DEL_BANCO_RECCEPTOR_BANORTE", "072");
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_TIPO_DE_CUENTA_CHEQUES", "01");
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_NUMERO_DE_CUENTA", 18);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_TIPO_DE_MOVIMIENTO", 0);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_IMPORTE_DE_IVA_LONGITUD", 8);
define("BANCOS_BANORTE_LAYOUT_INTEGRADO_NOMINA_FILTER_ESPACIOS_EN_BLANCO_DETALLE", 8);



define("BANCOS_SATANDER_LAYOUT_NOMINA", 5);
define("BANCOS_SATANDER_ARCHIVO_EXPORTAR", "satander");
define("BANCOS_SATANDER_LAYOUT_NOMINA_TIPO_DE_REGISTRO_ENCABEZADO", 1);
define("BANCOS_SATANDER_LAYOUT_NOMINA_NUMERO_SECUENCIA_ENCABEZADO", "00001");
define("BANCOS_SATANDER_LAYOUT_NOMINA_NUMERO_DE_SECUENCIA_LONGITUD", 5);
define("BANCOS_SATANDER_LAYOUT_NOMINA_NUMERO_SENTIDO", "E");
define("BANCOS_SATANDER_LAYOUT_NOMINA_CUENTA_DE_CARGO_LONGITUD", 16);
define("BANCOS_SATANDER_LAYOUT_NOMINA_DECIMALES_IMPORTE_LONGITUD", 2);

define("BANCOS_SATANDER_LAYOUT_NOMINA_TIPO_DE_REGISTRO_DETALLE", 2);
define("BANCOS_SATANDER_LAYOUT_NOMINA_NUMERO_SECUENCIA_DETALLE", "00002");

define("BANCOS_SATANDER_LAYOUT_NOMINA_NUMERO_DE_EMPLEADO_LONGITUD", 7);
define("BANCOS_SATANDER_LAYOUT_NOMINA_APELLIDO_PATERNO_LONGITUD", 30);
define("BANCOS_SATANDER_LAYOUT_NOMINA_APELLIDO_MATERNO_LONGITUD", 20);
define("BANCOS_SATANDER_LAYOUT_NOMINA_APELLIDO_NOMBRE_LONGITUD", 30);
define("BANCOS_SATANDER_LAYOUT_NOMINA_NUMERO_DE_CUENTA_LONGITUD", 16);
define("BANCOS_SATANDER_LAYOUT_NOMINA_IMPORTE_LONGITUD", 18);

define("BANCOS_SATANDER_LAYOUT_NOMINA_TIPO_DE_REGISTRO_SUMARIO", 3);
define("BANCOS_SATANDER_LAYOUT_NOMINA_NUMERO_DE_SECUENCIA", "0003");
define("BANCOS_SATANDER_LAYOUT_NOMINA_TOTAL_DE_REGISTROS_LONGITUD", 5);
define("BANCOS_SATANDER_LAYOUT_NOMINA_IMPORTE_TOTAL_LONGITUD", 18);

define("BANCOS_BANREGIO_LAYOUT_TRANSFERENCIAS_BANCOS", 6);
define("BANCOS_BANREGIO_ARCHIVO_EXPORTAR", "banregio");
define("BANCOS_BANREGIO_LAYOUT_TIPO_REGISTRO", "01");
define("BANCOS_BANREGIO_LAYOUT_LONGITUD", 6);
define("BANCOS_BANREGIO_LAYOUT_LONGITUD_RAZON_SOCIAL", 40);
define("BANCOS_BANREGIO_LAYOUT_DESCRIPCION_OPERACION", "Pago de nomina");
define("BANCOS_BANREGIO_LAYOUT_DESRIPCION_LONGITUD", 40);
define("BANCOS_BANREGIO_LAYOUT_CORREO_ELECTRONICO_LONGITUD", 50);
define("BANCOS_BANREGIO_LAYOUT_RFC_LONGITUD", 50);



define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS", 7);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_ARCHIVO_EXPORTAR", "afirme");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_NUMERO_DE_SECUENCIA_LONGITUD", 7);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_SERVICIO", "01");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_CODIGO_DIVISA", "01");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_MODALIDAD_MISMO_DIA", 1);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_BANCO_PRESENTADOR", "062");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_OPERACION", "04");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_DE_CUENTA_ORDENANTE", "01");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_NUMERO_DE_CUENTA_DEL_ORDENANTE_LONGITUD", 20);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_NOMBRE_ORDENANTE_LONGITUD", 40);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_RFC_ORDENANTE_LONGITUD", 18);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_NUMERO_OPERACIONES_LONGITUD", 7);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_IMPORTE_TOTAL_OPERACIONES_LONGITUD", 18);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_DESCRIPCION_DEL_LOTE_LONGITUD", 40);

define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_REGISTRO_DETALLE", "02");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_CODIGO_OPERACION_ABONO", "60");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_CODIGO_OPERACION_CARGO", "30");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_BANCO_RECEPTOR", "062");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_IMPORTE_DE_LA_OPERACION", 15);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_DE_CUENTA_DEL_RECEPTOR_CHEQUES", "01");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_DE_CUENTA_DEL_RECEPTOR_TARJETA_DEBITO", "03");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_DE_CUENTA_DEL_RECEPTOR_ABONO_VENTANILLA", "04");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_DE_CUENTA_DEL_RECEPTOR_TARJETA_CREDITO", "05");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_DE_CUENTA_DEL_RECEPTOR_REFERENCIA_AFIRME", "06");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_TIPO_DE_CUENTA_DEL_RECEPTOR_CLABE", "40");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_CUENTA_REFERENCIA_BENEFICIARIO_LONGITUD", 20);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_NOMBRE_RECEPTOR_LONGITUD", 40);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_RFC_CURP_RECEPTOR_LONGITUD", 18);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_REFERENCIA_DEL_SERVICIO_CON_EMISOR_LONGITUD", 40);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_NOMBRE_DEL_TITULAR_DEL_SERVICIO_LONGITUD", 40);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_IMPORTE_IVA_DE_LA_OPERACION_LONGITUD", 15);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_REFERENCIA_NUMERICA_DEL_ORDENANTE_LONGITUD", 7);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TERCEROS_REFERENCIA_LEYENDA_ORDENANTE_LONGITUD", 40);

define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_TIPO_REGISTRO_RESUMEN", "09");
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_NUMERO_DE_SECUENCIA_LONGITUD", 7);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_NUMERO_OPERACIONES_LONGITUD", 7);
define("BANCOS_AFIRME_LAYOUT_TRANSFERENCIAS_IMPORTE_TOTAL_DE_OPERACIONES_LONGITUD", 18);

define("REPORTE_CONSTANCIA_SUELDO_FORMA_37_DIRECTORIO_IMAGES", 'Reporteador/img_forma_37/');
define("REPORTE_CONSTANCIA_SUELDO_FORMA_37_PAGINA_UNO", 'forma_37-page-001.jpg');
define("REPORTE_CONSTANCIA_SUELDO_FORMA_37_PAGINA_DOS", 'forma_37-page-002.jpg');
define("REPORTE_CONSTANCIA_SUELDO_FORMA_37_PAGINA_TRES", 'forma_37-page-003.jpg');
define("REPORTE_EMPLEADOS_ESTADISTICAS", 1);
define("REPORTE_AHORROS_Y_PRESTAMOS_POR_EMPLEADO", 7);
define("REPORTE_ACUMULADOS_ANUALES_DETALLE", 9);
define("REPORTE_ACUMULADOS_ANUALES_RESUMEN", 8);
define("REPORTE_CAPTURA_INFONAVIT_ESPECIAL", 10);
define("REPORTE_COMISIONES_ESPECIAL", 11);
define("REPORTE_CALCULO_ANUAL_ISR", 23);
define("REPORTE_CALCULO_ANUAL_ISR_MONTOS", 24);
define("REPORTE_CONSTANCIA_DE_SUELDO_FORMA_37", 25);
define("REPORTE_CREDITO_INFONAVIT_LISTADO_EMPLEADOS", 2);
define("REPORTE_CUENTAS_PARA_DEPOSITO", 3);
define("REPORTE_EMPLEADOS_POR_REGISTRO_PATRONAL", 4);
define("REPORTE_EMPLEADOS_POR_TIPO_NOMINA", 5);
define("REPORTE_DETERMINACION_DE_PRIMA_DE_RIESGO", 27);
define("REPORTE_ESTATUS_PERIODOS", 28);
define("REPORTE_FACTURA_CLIENTE", 29);
define("REPORTE_IMPUESTO_NUEVO_EMPRESAS", 30);
define("REPORTE_INFONAVIT_ESPECIAL", 31);
define("REPORTE_RECIBO_NOMINA", 32);
define("REPORTE_SALARIO_INTEGRADO_EMPLEADO", 6);
define("REPORTE_FACTURA_CLIENTE_MENSUAL", 33);
define("REPORTE_FACTURA_CLIENTE_TIPO_NOMINA", 34);
define("REPORTE_LISTADO_NOMINA", 35);
define("REPORTE_LISTADO_NOMINA_GRAN_TOTAL", 37);
define("REPORTE_LISTADO_NOMINA_SUBTOTAL_TOTAL", 38);

define("REPORTE_TIPO_LISTADO_EJE_Y_PRIMER_ROW", 38);
define("REPORTE_TIPO_LISTADO_LIMIT_ROWS_POR_PAGINA", 58);
define("REPORTE_TIPO_LISTADO_INCREMENTO_POR_ROW", 4);

define("REPORTE_FILTRO_TODOS", 1);
define("REPORTE_FILTRO_LISTADO", 2);
define("REPORTE_FILTRO_ACTIVO", 3);

define("REPORTE_FORMATO_PDF", 1);
define("REPORTE_FORMATO_EXCEL", 2);
define("REPORTE_FORMATO_CSV", 3);


define("CALCULO_ISR_REVISAR_RFC_CURP_REVISAR_TODOS", 1);
define("CALCULO_ISR_REVISAR_RFC_CURP_REVISAR_SOLO_FALTANTES", 2);
define("CALCULO_ISR_REVISAR_RFC_CURP_REVISAR_NO_REVISAR", 3);

define("PAIS_MEXICO", 1);
define("NOMBRE_ARCHIVO_DIM", "DIM");


define("CALCULO_ISR_DIM_APELLDO_PATERNO_LENGTH", 43);
define("CALCULO_ISR_DIM_APELLDO_MATERNO_LENGTH", 43);
define("CALCULO_ISR_DIM_NOMBRE_LENGTH", 43);
define("CALCULO_ISR_DIM_PROPORCION_SUBCIDIO_APLICADA_LENGTH", 6);





/* End of file constants.php */
/* Location: ./application/config/constants.php */